# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x07\x65xample\"z\n\x0csend_request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\x05\x12\x17\n\x0f\x65vent_interface\x18\x04 \x01(\t\x12\x13\n\x0b\x65vent_money\x18\x05 \x01(\x05\x12\x10\n\x07\x62\x61lance\x18\x90\x03 \x01(\x05\"=\n\x0cget_response\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x07\x62\x61lance\x18\xb0\t \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2M\n\x0cTransactions\x12=\n\x0bMsgDelivery\x12\x15.example.send_request\x1a\x15.example.get_response\"\x00\x62\x06proto3'
)




_SEND_REQUEST = _descriptor.Descriptor(
  name='send_request',
  full_name='example.send_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.send_request.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='example.send_request.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='example.send_request.event_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_interface', full_name='example.send_request.event_interface', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_money', full_name='example.send_request.event_money', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance', full_name='example.send_request.balance', index=5,
      number=400, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=148,
)


_GET_RESPONSE = _descriptor.Descriptor(
  name='get_response',
  full_name='example.get_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.get_response.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance', full_name='example.get_response.balance', index=1,
      number=1200, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='example.get_response.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['send_request'] = _SEND_REQUEST
DESCRIPTOR.message_types_by_name['get_response'] = _GET_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

send_request = _reflection.GeneratedProtocolMessageType('send_request', (_message.Message,), {
  'DESCRIPTOR' : _SEND_REQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.send_request)
  })
_sym_db.RegisterMessage(send_request)

get_response = _reflection.GeneratedProtocolMessageType('get_response', (_message.Message,), {
  'DESCRIPTOR' : _GET_RESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.get_response)
  })
_sym_db.RegisterMessage(get_response)



_TRANSACTIONS = _descriptor.ServiceDescriptor(
  name='Transactions',
  full_name='example.Transactions',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=213,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='MsgDelivery',
    full_name='example.Transactions.MsgDelivery',
    index=0,
    containing_service=None,
    input_type=_SEND_REQUEST,
    output_type=_GET_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTIONS)

DESCRIPTOR.services_by_name['Transactions'] = _TRANSACTIONS

# @@protoc_insertion_point(module_scope)
